paths:
  config_dir: "${oc.env:YAML_DIR}"
  calib_dir: "${paths.config_dir}/../src/Calibration"

  # input
  scene_dir: "${paths.config_dir}/../data/scenes/${env}/${dataset_name}"
  charuco_board_path: "${paths.calib_dir}/data/charuco_boards/${charuco_board}"
  sensor_path: "${paths.calib_dir}/data/sensors/${sensor}.yml"
  aruco_struct: "${paths.config_dir}/aruco_struct.yaml"

  # output
  save_dir: "${paths.config_dir}/../data/${save_name}/calib_data"
  save_scene: "${paths.save_dir}/scene" # DON'T CHANGE!
  out_dir: "${paths.save_dir}/output" # DON'T CHANGE!
  in_dir: "${paths.save_dir}/input" # DON'T CHANGE!
  results_final_dir: "${global_calibration.paths.out_dir}" # DON'T CHANGE!

save_name: "cvl1"
# charuco_board: "charuco_7x5_3boards.yml"
charuco_board: "charuco_11x9_cvl.yml"
# charuco_board: "charuco_9x11_cvl_thin.yml"
sensor: "Basler_ace2_a2A1920"

# env: "Blender"
# dataset_name: "blender_1_full"
#
env: "Basler"
dataset_name: "default"

intrinsics_calibration:
  name: "Intrinsics calibration"
  do: False
  generate_data:
    do: False
    per_cam: True
    automatic: True
    dist_thresh_auto: 10000 # if automaic
    basler_params:
      sRGB: True
      pixel_format: BayerRG8
      # pixel_format: Mono8
      # pixel_format: RGB8
      exposure_time: 10000
      signal_period: 1000

  paths:
    out_dir: "${paths.out_dir}/intrinsics" # DON'T CHANGE!
    in_dir: "${paths.in_dir}/intrinsics" # DON'T CHANGE!
    cache_dir: "Data/intrinsics" # DON'T CHANGE!
    charuco_board_path: "${paths.charuco_board_path}"
    sensor_path: "${paths.sensor_path}"
  calibration:
    do: True
    fix_intr: False
    intr_start: "None"

global_calibration:
  name: "Global calibration"
  do: True
  generate_data:
    do: False
    per_cam: False
    automatic: False
    dist_thresh_auto: 10000 # if automaic
    basler_params:
      sRGB: True
      pixel_format: BayerRG8
      # pixel_format: Mono8
      # pixel_format: RGB8
      exposure_time: 20000
  paths:
    out_dir: "${paths.out_dir}/global" # DON'T CHANGE!
    in_dir: "${paths.in_dir}/global" # DON'T CHANGE!
    cache_dir: "Data/global" # DON'T CHANGE!
    charuco_board_path: "${paths.charuco_board_path}"
    sensor_path: "${paths.sensor_path}"
  calibration:
    do: True
    fix_intr: True
    intr_start: "${paths.out_dir}/intrinsics/calibrated_cameras_data.yml" # DON'T CHANGE!
    # intr_start: "None"

compute_world: True

intr: True
blend_dir: ""
blend_dataset: ""
no_render: True
interactive: True

correction:
  iterations: 500
  device: "cuda"
  debug: False
  lr: 0.0001
