interactive: True
scenes_dir: "../data/scenes/" #relative path to scenes
save_dir: "../data/calib_data" # relative path to calib data
calib_dir: "../src/Calibration" # relative path to calib 

env: "Basler"
dataset_name: "default"

# env: "Blender"
# dataset_name: "blender_1_full"

save_name: "cvl1"
charuco_board: "charuco_7x5_3boards.yml"
generate_data: True
manual_intr: False
manual: True
intr: True
blend_dir: ""
blend_dataset: ""
no_render: True
dist_thresh_auto: 50

# no_basl_gen: False
