paths:
  config_dir: "${oc.env:YAML_DIR}"
  # pose_estimator_dir: "${paths.config_dir}/../src/ConveyorPoseEstimator"
  # pose_estimator_cfg: "${paths.config_dir}/pose_estimator.yaml"

  # input
  calib_data_dir: "${paths.config_dir}/../data/${save_name}/light_calib_data"
  color_correction_data_dir: "${paths.config_dir}/../data/${save_name}/color_correction_data"
  # calib_data_dir: "${paths.config_dir}/../data/${save_name}/calib_data"
  pose_estimator_data_dir: "${paths.config_dir}/../data/${save_name}/pose_estimator_data"
  led_cfg_dir: "${paths.config_dir}/leds.yaml"
  blender_dir: "${paths.calib_data_dir}/scene" # scene folder where there is the blender scene relative to calibration data

  save_dir: "${oc.env:YAML_DIR}/../data/${save_name}/collector_data"
  save_scene_dir: "${paths.save_dir}/scene"
  save_mitsuba_scene: "${paths.save_scene_dir}/mitsuba_scene"
  mesh_dir: "${paths.save_dir}/mesh"
  captured_dir: "${paths.save_dir}/captured"
  # light_data_dir: "${paths.config_dir}/../data/${dataset_name}/light_calib_data"
  # calib_data_dir: "${paths.config_dir}/../data/${dataset_name}/calib_data"

save_name: "cvl1"

crop: True
sRGB: False
strategy: UpcomingImage

objects:
  - "cj_lowpoly"

normalization:
  color_correction: True
  exposure_time_ref: 10000

led_amp: 1.5

exposure_time: 25000
signal_period: 10000
range_half: 15
# velocity: (8.*1600/0.34)*0.00145
velocity: "0"

collect_manual:
  # signal_period: 100000
  signal_period: 500000
  exposure_time: 1000

collect_track:
  signal_period: 100000
  exposure_time: 7500
  velocity: (8.5*1600/0.35)*0.002

collect_sequence:
  sequence: # list of couples (light_id, value on x axis)
    # - [ 0, -0.25 ]
    - [0, 1000]
    # - [ 1, -0.15 ]
    # - [ 0, -0.12 ]
    # - [ 2, -0.10 ]
    # - [ 1, -0.05 ]
    # - [ 0,  0.00 ]
    # - [ 3,  0.05 ]
    # - [ 2,  0.10 ]
    # - [ 0,  0.12 ]
    # - [ 3,  0.15 ]
    #
    #
    #

collect_video:
  init: "pose"
  # init: 40 # start point in frames
  end: "pose"
  # end: 40 # start point in frames
  out: "png"

n_frames: 20
