paths:
  config_dir: "${oc.env:YAML_DIR}"
  data_in_dir: "${oc.env:YAML_DIR}/../data/${save_name}/calib_data" # data folder where there are input conditions (calibration data)
  calib_scene_dir: "${paths.data_in_dir}/scene/"
  calib_res_dir: "${paths.data_in_dir}/output/global"
  calib_src: "${oc.env:YAML_DIR}/../src/Calibration/src"
  calib_cfg: "${oc.env:YAML_DIR}/calibration.yaml"
  collector_in_dir: "${oc.env:YAML_DIR}/../data/${save_name}/collector_edge_pose_data_conv"
  data_out_dir: "${oc.env:YAML_DIR}/../data/${save_name}/edged_pose_estim_conv"
  images_dir: "${paths.data_out_dir}/images"
  mesh_path: "${oc.env:YAML_DIR}/../data/scenes/Basler/meshes/conv.obj"
  collector_dir: "${oc.env:YAML_DIR}/../src/Collector"
  collector_path: "${paths.collector_dir}/collect.py"
  captured_dir: "${paths.collector_in_dir}/captured"
  collector_cfg: "${oc.env:YAML_DIR}/collector_edge_pose_estim_conv.yaml"
  led_cfg: "${oc.env:YAML_DIR}/leds.yaml"

save_name: "cvl1"
obj_name: "belt"

opt:
  device: "cuda"
  # device: "cpu"
  iterations: 100

  # # l2
  # lr_scl_obj: 0.0000001
  # lr_eul_obj: 0.000001
  # lr_pos_obj: 0.00000001
  # lr_eul_cam: 0.0000001
  # lr_pos_cam: 0.00000001
  # lr_eul_brd: 0.00000
  # lr_pos_brd: 0.000000
  # pow: "2"

  # l2
  lr_scl_obj: 0.0
  lr_eul_obj: 0.0
  lr_pos_obj: 0.0
  lr_eul_cam: 0.0003
  lr_pos_cam: 0.00003
  lr_eul_brd: 0.0003
  lr_pos_brd: 0.00003
  pow: "1"

  # # l2 adam
  # lr_scl_obj: 0.0001
  # lr_eul_obj: 0.001
  # lr_pos_obj: 0.00001
  # lr_eul_cam: 0.0001
  # lr_pos_cam: 0.00001
  # lr_eul_brd: 0.00
  # lr_pos_brd: 0.000
  # matrix_world[:,1:3]# pow: "2"
  # pow: "2 + (2*(it/${opt.iterations}))"
  #
  # reg_lambda: 1
  # reg_lambda: 0
  # reg_lambda: 0.2
  reg_lambda: 0.001
  # reg_lambda: 0.00001

collect_images: False
# canny_sigma: 0.75
canny_sigma: 0.05
# canny_sigma: 1.5
exp_distmap: 0.4
threshold_edge_synt: 1.
# threshold_edge_synt: 1.
# threshold_edge_synt: 0.2
exposure_time: 10000
fixed: None

with_boards: True
debug_edges: True
debug_boards: True
wk_edges: 0
obj_only_x: False
obj_shared_rot: True
# obj_shared_yz: False
obj_fixed_e1e2: True
opt_cams: True
obj_scale: False
opt_boards: True
images_only: True
