
lights:
  n_lights: 1

aruco:
  dict:
  number:

tuning:
  signal_period: 100000
  exposure_time: 250
  min_exp_time: 20
  optimal_intensity: 245
  K_et: 25
  # et_coeff: 0.1
  batch_size: 20
  n_tests: 30
  std_thresh: 0.5
  
plane_estimator:
  exposure_time: 40000
  signal_period: 100000
  aruco_pnp:
    aruco_cfg:
      dict_n: 4
      dict_size: 50
      range_idxs: [0,0]
    struct: 
      positions:
        - [0, 0, 0]
        - [0, 1, 0]
        - [0, 2, 0]
        - [0, 3, 0]
        - [0, 4, 0]
        - [1, 0, 0]
        - [1, 1, 0]
        - [1, 2, 0]
        - [1, 3, 0]
        - [1, 4, 0]
      eulers:
        - [0, 0, 0]
        - [0, 0, 0]
        - [0, 0, 0]
        - [0, 0, 0]
        - [0, 0, 0]
        - [0, 0, 0]
        - [0, 0, 0]
        - [0, 0, 0]
        - [0, 0, 0]
        - [0, 0, 0]
      ids:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
      marker_length: 1
      scale: 1
    n_aruco_thresh: 0

calib_yaml: "./calibration.yaml"
sceneload_dir: "../src/SceneLoader/"
