
paths:
  # calib_yaml: "${oc.env:YAML_DIR}/calibration.yaml"
  calib_data_dir: "${oc.env:YAML_DIR}/../data/${save_name}/calib_data" 
  leds_yaml: "${oc.env:YAML_DIR}/leds.yaml"
  # save_dir: "../data/light_calib_data/${save_name}"
  light_calib_dir: "${oc.env:YAML_DIR}/../src/LightCalib"
  save_dir: "${oc.env:YAML_DIR}/../data/${save_name}/light_calib_data"

save_name: "cvl1"

lights:
  n_lights: 1
  blender_size: 0.01

aruco:
  dict:
  number:

# tuning:
#   signal_period: 100000
#   exposure_time: 1000
#   min_exp_time: 1000
#   optimal_intensity: 249
#   K_et: 25
#   # et_coeff: 0.1
#   batch_size: 75
#   n_tests: 10
#   std_thresh: 0.5

calib:
  signal_period: 100000
  exp_time_ray_extraction: 800
  batch_size: 75
  std_thresh: 0.5

# save_imgs: True
led_intensity: 0.0001
n_images: 3

plane_estimator:
  exposure_time: 15000
  signal_period: 1000
  integrate_n_frames: 75
  position_thresh: 0.1
  orientation_thresh: 0.1
  aruco_pnp:
    aruco_cfg:
      dict_n: 4
      dict_size: 50
      range_idxs: [0,19]

    # LAPTOP
    struct: 
      positions:
        - [-4, -9, -0.0023]
        - [-4, -7, -0.0023]
        - [-4, -5, -0.0023]
        - [-4, -3, -0.0023]
        - [-4, -1, -0.0023]
        - [-4,  1, -0.0023]
        - [-4,  3, -0.0023]
        - [-4,  5, -0.0023]
        - [-4,  7, -0.0023]
        - [-4,  9, -0.0023]
        - [ 4, -9, -0.0023]
        - [ 4, -7, -0.0023]
        - [ 4, -5, -0.0023]
        - [ 4, -3, -0.0023]
        - [ 4, -1, -0.0023]
        - [ 4,  1, -0.0023]
        - [ 4,  3, -0.0023]
        - [ 4,  5, -0.0023]
        - [ 4,  7, -0.0023]
        - [ 4,  9, -0.0023]
      eulers:
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
        - [0, 0, 90]
      ids:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
      convention: "YXZ"
      marker_length: 1
      scale: 0.0172
      # scale: 0.0229
      
    # TABLET
    # struct: 
    #   positions:
    #     - [-2, -4, -0.0023]
    #     - [-2, -2, -0.0023]
    #     - [-2,  0, -0.0023]
    #     - [-2,  2, -0.0023]
    #     - [-2,  4, -0.0023]
    #     - [ 2, -4, -0.0023]
    #     - [ 2, -2, -0.0023]
    #     - [ 2,  0, -0.0023]
    #     - [ 2,  2, -0.0023]
    #     - [ 2,  4, -0.0023]
    #   eulers:
    #     - [0, 0, 90]
    #     - [0, 0, 90]
    #     - [0, 0, 90]
    #     - [0, 0, 90]
    #     - [0, 0, 90]
    #     - [0, 0, 90]
    #     - [0, 0, 90]
    #     - [0, 0, 90]
    #     - [0, 0, 90]
    #     - [0, 0, 90]
    #   ids:
    #     - 0
    #     - 1
    #     - 2
    #     - 3
    #     - 4
    #     - 5
    #     - 6
    #     - 7
    #     - 8
    #     - 9
    #   convention: "YXZ"
    #   marker_length: 1
    #   # scale: 0.02
    #   scale: 0.0229
      
    n_aruco_thresh: 0

