
paths:

  # input
  # data_in_dir: "${oc.env:YAML_DIR}/../data/${save_name}/pose_estimator_data"
  # xml_path: "${paths.data_in_dir}/scene/mitsuba_scene/scene.xml"

  collector_dir: "${oc.env:YAML_DIR}/../src/Collector"
  data_in_dir: "${oc.env:YAML_DIR}/../data/${save_name}/collector_data"
  xml_path: "${paths.data_in_dir}/scene/mitsuba_scene/scene.xml"
  pose_estimator_dir: "${oc.env:YAML_DIR}/../src/ConveyorPoseEstimator"
  pose_estimator_config: "${oc.env:YAML_DIR}/../configs/pose_estimator.yaml"
  out_dir: "${oc.env:YAML_DIR}/../data/${save_name}/solver_data"




save_name: "cvl1"

renderer:
  # variant: "scalar_rgb"
  # variant: "llvm_ad_rgb"
  variant: "cuda_ad_rgb"
  spp: 12
  spp_max: 1
  spp_max_inference: 1
  seed: 666
  max_depth: 2
  rr_depth: 18
  obj_names: ["elm__2"]



optim:
  parameters:
    # - ["$elm__2.bsdf.reflectance.value", [0,1] ]
    - ["$elm__2.bsdf.brdf_0.base_color.data", [[0,0.999], 3] ]
    # - ["${optim.obj_name}.bsdf.brdf_0.roughness.data", [[0,0.999], 1]]
    # - ["${optim.obj_name}.bsdf.brdf_0.metallic.value", [[0,0.999], 1]]
    - ["elm__6.to_world", [null, null]]
    # - ["elm__7.to_world", [null, null]]
    # - ["elm__6.x_fov", [null, null]]
    # - ["elm__7.x_fov", [null, null]]
    # - ["elm__9.position", [null, null]]
    # - ["${optim.obj_name}.bsdf.brdf_0.metallic.value", [[0,0], null]]
    # - ["${optim.obj_name}.bsdf.brdf_0.roughness.value", [0,1] ]
    # - ["elm__85.intensity.value", [0,10] ]
    #elm__6.to_world
  params_extra:
    - [["y","z","e2"], "shared", ["elm__2","elm__3"]]
    - [["x"], "singular", ["elm__2","elm__3"]]
  lr: 0.1

  # multi
  # epochs: 30
  # early_stop_thresh: [ 0.001, 0.001, 0.001, 0.001, 0.001 ]
  # res: [256, 512, 1024, 2048, 4096]
  
  # single
  epochs: 60
  early_stop_thresh: [  0.00001 ]
  res: [ 4096 ]





