
paths:

  # input
  # data_in_dir: "${oc.env:YAML_DIR}/../data/${save_name}/pose_estimator_data"
  # xml_path: "${paths.data_in_dir}/scene/mitsuba_scene/scene.xml"

  collector_dir: "${oc.env:YAML_DIR}/../src/Collector"
  data_in_dir: "${oc.env:YAML_DIR}/../data/${save_name}/collector_data"
  xml_path: "${paths.data_in_dir}/scene/mitsuba_scene/scene.xml"
  pose_estimator_dir: "${oc.env:YAML_DIR}/../src/ConveyorPoseEstimator"
  pose_estimator_config: "${oc.env:YAML_DIR}/../configs/pose_estimator.yaml"
  out_dir: "${oc.env:YAML_DIR}/../data/${save_name}/solver_data"




save_name: "cvl1"

renderer:
  # variant: "scalar_rgb"
  # variant: "llvm_ad_rgb"
  variant: "cuda_ad_rgb"
  spp: 4
  # pixel_batch: 10000
  pixel_batch: null
  # spp_max: 12
  spp_max_inference: 1
  seed: 666
  max_depth: 3
  rr_depth: 18
  obj_names: ["cj_machined", "cj_unmachined"]
  # obj_names: ["cj_machined"]
  mode: "mask"
  mask_expand: 0

replace:

  # # const environment
  # environment:
  #   type: 'constant'
  #   radiance:
  #       type: 'rgb'
  #       value: [0.01,0.01,0.01]

  # # COMPOSITION
  # mat-machined:
  #   type: 'twosided'
  #   id: 'mat-machined'
  #   bsdf: 
  #     type: 'blendbsdf'
  #     weight: 0.75
  #     bsdf_0:
  #       type: 'roughconductor'
  #       material: 'Al'
  #       alpha_u: 0.005
  #       alpha_v: 0.36
  #       # alpha_v: 0.005
  #     bsdf_1:
  #       type: 'roughconductor'
  #       material: 'Al'
  #       alpha_u: 0.45
  #       alpha_v: 1.
  # mat-unmachined:
  #   type: 'twosided'
  #   id: 'mat-unmachined'
  #   bsdf: 
  #     type: 'principled'
  #     base_color:
  #       type: 'rgb'
  #       value: [0.63, 0.63, 0.63]
  #     metallic: 0.55
  #     specular: 0.5
  #     roughness: 0.65
# optim:
  # parameters:
  #   # emitters
  #   # - ['cj_machined.bsdf.brdf_0.weight.value', [[0, 0.999], 1]]
  #   # - ['environment.radiance.value', [[0,1000000], 3] ]
  #   # - ['cj_machined.bsdf.brdf_0.bsdf_0.alpha_u.value', [[0, 0.999], 1]]
  #   # - ['cj_machined.bsdf.brdf_0.bsdf_0.alpha_v.value', [[0, 0.999], 1]]
  #   # - ['cj_machined.bsdf.brdf_0.bsdf_1.alpha_u.value', [[0, 0.999], 1]]
  #   # - ['cj_machined.bsdf.brdf_0.bsdf_1.alpha_v.value', [[0, 0.999], 1]]
  #   - ['cj_unmachined.bsdf.brdf_0.base_color.value', [[0, 0.999], 3]]
  #   # - ['cj_unmachined.bsdf.brdf_0.metallic.value', [[0, 0.999], 1]]
  #   # - ['cj_unmachined.bsdf.brdf_0.roughness.value', [[0, 0.999], 1]]


  # ANISOTROPIC SIMPLE
  mat-machined:
    type: 'twosided'
    id: 'mat-machined'
    bsdf: 
      type: 'roughconductor'
      material: 'Al'
      alpha_u: 0.0
      alpha_v: 0.0
optim:
  parameters:
    # emitters
    # - ['environment.radiance.value', [[0,1000000], 3] ]

  
  # # ANISOTROPIC TEXTURE
  # mat-machined:
  #   type: 'twosided'
  #   id: 'mat-machined'
  #   bsdf: 
  #     type: 'roughconductor'
  #     material: 'Al'
  #     alpha_u:
  #       type: 'bitmap'
  #       filename: "${paths.data_in_dir}/scene/alpha_u.png"
  #     alpha_v:
  #       type: 'bitmap'
  #       filename: "${paths.data_in_dir}/scene/alpha_v.png"
  # optim:
  #   parameters:
  #     # emitters
  #     - ['environment.radiance.value', [[0,1000000], 3] ]

  # # PRINCIPLED SIMPLE
  # mat-machined:
  #   type: 'twosided'
  #   id: 'mat-machined'
  #   bsdf: 
  #     type: 'principled'
  #     base_color:
  #       type: 'rgb'
  #       value: [1., 0., 0.]
  #     metallic: 0.
  #     specular: 0.5
  #     roughness: 1.
# optim:
  # parameters:
# #     # emitters
# #     - ['environment.radiance.value', [[0,1000000], 3] ]
  #   # - ['cj_machined.bsdf.brdf_0.roughness.value', [[0,0.999], 1] ]
  #   - ['cj_machined.bsdf.brdf_0.base_color.data', [[0,0.999], 3] ]
  #   - ['cj_unmachined.bsdf.brdf_0.base_color.data', [[0,0.999], 3] ]
  
  # # PRINCIPLED TEXTURE
  # mat-machined:
  #   type: 'twosided'
  #   id: 'mat-machined'
  #   bsdf: 
  #     type: 'principled'
  #     base_color:
  #       type: 'bitmap'
  #       filename: "${paths.data_in_dir}/scene/base_color.png"
  #     metallic: 0.
  #     specular: 0.5
  #     roughness: 1.
# optim:
  # parameters:
# #     # emitters
# #     - ['environment.radiance.value', [[0,1000000], 3] ]
  #   # - ['cj_machined.bsdf.brdf_0.roughness.value', [[0,0.999], 1] ]
  #   - ['cj_machined.bsdf.brdf_0.base_color.data', [[0,0.999], 3] ]
  #   - ['cj_unmachined.bsdf.brdf_0.base_color.data', [[0,0.999], 3] ]
  
# optim:
#   parameters:
# #     # emitters
# #     - ['environment.radiance.value', [[0,1000000], 3] ]
#     - ['cj_machined.bsdf.brdf_0.roughness.value', [[0,0.999], 1] ]
#     - ['cj_machined.bsdf.brdf_0.base_color.data', [[0,0.999], 3] ]
#     - ['cj_unmachined.bsdf.brdf_0.base_color.data', [[0,0.999], 3] ]


    
  pose_refinement:
    lr: 0.00003
    reg_coeff: 0
    elements:
      - [["cj_machined","cj_unmachined"], ["y:share", "z:share", "e2:share", "x:sing"]]
      # - [["cj_machined","cj_unmachined"], ["y:share", "z:share", "e2:share"]]

  lr: 0.05
  # lr: 0.015
  # lr: 0.007
  # lr: 0.00001

  # multi
  # epochs: 30
  # early_stop_thresh: [ 0.001, 0.001, 0.001, 0.001, 0.001 ]
  # res: [256, 512, 1024, 2048, 4096]
  
  # single
  epochs: 1000
  # early_stop_thresh: [  0.00001 ]
  early_stop_thresh: [  0.0 ]
  res: [ 2046 ]





