
paths:

  # input
  data_in_dir: "${oc.env:YAML_DIR}/../data/${save_name}/pose_estimator_data"
  xml_path: "${paths.data_in_dir}/scene/mitsuba_scene/scene.xml"
  pose_estimator_dir: "${oc.env:YAML_DIR}/../src/ConveyorPoseEstimator"
  pose_estimator_config: "${oc.env:YAML_DIR}/../configs/pose_estimator.yaml"



save_name: "cvl1"

renderer:
  # variant: "scalar_rgb"
  # variant: "llvm_ad_rgb"
  spp: 32
  variant: "cuda_ad_rgb"
  seed: 666
  max_depth: 8
  rr_depth: 5



optim:
  obj_name: "elm__2"




