paths:
  config_dir: "${oc.env:YAML_DIR}"
  collector_dir: "${paths.config_dir}/../src/Collector"
  led_cfg: "${paths.config_dir}/leds.yaml"
  mesh_path: "${oc.env:YAML_DIR}/../data/scenes/Basler/meshes/cj_lowpoly.obj"
  save_data: "${oc.env:YAML_DIR}/../data/${save_name}/nerf_data"

save_name: "cvl1"

collect:
  # texture_res: 8192
  texture_res: 4096
  # texture_res: 3000
  #texture_res: 2800
  # texture_res: 2240
  # texture_res: 2046
  device: "cpu"
  train:
    collect_images: False
    # range_pose_ids: [0, 300]
    range_pose_ids: null
    collect_training_data: True
    type: "collect_video"
    collector_cfg: "${paths.config_dir}/collector_nerf_text_train.yaml"
    subfolder: "train"
    img_id_range: [0, 1000]
    # img_id_range: [2, 3]

  eval:
    collect_images: False
    collect_training_data: False
    type: "collect_manual_while_track"
    collector_cfg: "${paths.config_dir}/collector_nerf_text_eval.yaml"
    subfolder: "eval"

train:
  device: "cuda"
  epochs: 1000
  lr: 0.001
  reg_coeff: 0.001
  data_loader_params:
    batch_size: 131072
    shuffle: True
    num_workers: 8
    persistent_workers: True
    pin_memory: True
  save_every: 1
  save_model: False
  save_text: True
  eval_model: False
  load: False

eval:
  device: "cuda"
  chunk_size: 1000000

model:
  hidden_size: 256
  n_layers: 5

  # encoder_x:
  #   type: "None"
  #   kwargs:
  #     dim: 1

  encoder_x:
    type: "frequency"
    kwargs:
      dim: 1
      n_levels: 10

  # encoder_x:
  #   type: "gridencoder"
  #   kwargs:
  #     input_dim: 2

  # encoder_uv:
  #   type: "None"
  #   kwargs:
  #     dim: 1

  # encoder_uv:
  #   type: "None"
  #   kwargs:
  #     dim: 2

  # encoder_uv:
  #   type: "frequency"
  #   kwargs:
  #     dim: 2
  #     n_levels: 8

  encoder_uv:
    type: "multi_res_hash_grid"
    kwargs:
      dim: 2
      n_levels: 16
      n_features_per_level: 2
      finest_resolution: "${collect.texture_res}/2"
