paths:
  config_dir: "${oc.env:YAML_DIR}"
  collector_dir: "${paths.config_dir}/../src/Collector"
  led_cfg: "${paths.config_dir}/leds.yaml"
  mesh_path: "${oc.env:YAML_DIR}/../data/scenes/Basler/meshes/cj_lowpoly.obj"
  save_data: "${oc.env:YAML_DIR}/../data/${save_name}/porosity_detector"

save_name: "cvl1"

collect:
  # texture_res: 8192
  texture_res: 4096
  # texture_res: 3000
  #texture_res: 2800
  # texture_res: 2240
  # texture_res: 2046
  device: "cpu"
  train:
    collect_images: False
    # range_pose_ids: [0, 300]
    range_pose_ids: null
    collect_training_data: True
    # type: "collect_manual_while_track"
    type: "collect_video"
    collector_cfg: "${paths.config_dir}/collector_porosity_detector_train.yaml"
    subfolder: "train"
    img_id_range: [0, 99999]
    reset: False

  eval:
    collect_images: False
    # range_pose_ids: [0, 300]
    range_pose_ids: null
    collect_training_data: False
    # type: "collect_manual_while_track"
    type: "collect_video"
    collector_cfg: "${paths.config_dir}/collector_porosity_detector_eval.yaml"
    subfolder: "eval"
    img_id_range: [0, 99999]
    reset: False

train:
  device: "cuda"
  epochs: 1000
  load: False
  lr: 0.001
  patch_size: 128
  fill_iterations: 10
  fill_pixels: 5
  pore_size_range: [2, 20]
  pow_range: [1, 2]
  n_gaussians: 3
  intensity_drop_range: [0.4, 0.8]
  mask_thresh: 0.5
  pore_generation_ratio: 0.5
  eval_every: 10
  stride_factor: 0.5
  chunk_size_eval: 64
  dice_weight: 0.5

  model:
    name: "resnet18"
    input_channels: 3
    encoder_depth: 3
    decoder_channels: [128, 64, 32]
    decoder_use_batchnorm: "True"
    load_weights: True
  data_loader_params:
    batch_size: 64
    shuffle: True
    num_workers: 8
    persistent_workers: False
    pin_memory: False
