wandb_version: 1

paths:
  desc: null
  value: '{''config_dir'': ''/home/emcarus/Desktop/git_repos/diff_path/configs'',
    ''collector_dir'': ''/home/emcarus/Desktop/git_repos/diff_path/src/Collector'',
    ''led_cfg'': ''/home/emcarus/Desktop/git_repos/diff_path/configs/leds.yaml'',
    ''mesh_path'': ''/home/emcarus/Desktop/git_repos/diff_path/data/scenes/Basler/meshes/cj_lowpoly.obj'',
    ''save_data'': ''/home/emcarus/Desktop/git_repos/diff_path/data/cvl1/porosity_detector'',
    ''mask_path'': ''/home/emcarus/Desktop/git_repos/diff_path/data/scenes/Basler/meshes/mask_machined.png''}'
save_name:
  desc: null
  value: cvl1
wandb:
  desc: null
  value: '{''project'': ''porosity'', ''disabled'': False, ''log_images_eval'': True}'
collect:
  desc: null
  value: '{''texture_res'': 4096, ''device'': ''cpu'', ''train'': {''collect_images'':
    False, ''range_pose_ids'': None, ''collect_training_data'': False, ''compute_textures'':
    False, ''has_labels'': False, ''type'': ''collect_video'', ''collector_cfg'':
    ''/home/emcarus/Desktop/git_repos/diff_path/configs/collector_porosity_detector_train.yaml'',
    ''subfolder'': ''train'', ''img_id_range'': [0, 99999], ''masked'': True}, ''eval'':
    {''collect_images'': False, ''range_pose_ids'': None, ''collect_training_data'':
    True, ''compute_textures'': False, ''has_labels'': True, ''type'': ''collect_video'',
    ''collector_cfg'': ''/home/emcarus/Desktop/git_repos/diff_path/configs/collector_porosity_detector_eval.yaml'',
    ''subfolder'': ''eval'', ''img_id_range'': [0, 99999], ''masked'': True}, ''min_patch_ratio'':
    0.08}'
eval:
  desc: null
  value: '{''device'': ''cuda'', ''masked'': True, ''ensemble_n'': 3, ''eval_thresh'':
    2, ''model'': ''ensemble'', ''show_patches'': True, ''data_loader_params'': {''batch_size'':
    128, ''shuffle'': False, ''num_workers'': 8, ''persistent_workers'': False, ''pin_memory'':
    False}}'
train:
  desc: null
  value: '{''device'': ''cuda'', ''seed'': 42, ''epochs'': 11, ''load'': True, ''lr'':
    0.0001, ''weight_decay'': 0.0, ''patch_size'': 160, ''fill_iterations'': 10, ''fill_kernel'':
    3, ''fill_nn'': 5, ''normalize_colors'': True, ''channels'': 1, ''concatenate_mask'':
    False, ''loss'': {''dice'': {''weight'': 0.0}, ''bce'': {''weight'': 0.0}, ''tversky'':
    {''weight'': 1.0, ''params'': {''mode'': ''binary'', ''alpha'': 0.8, ''beta'':
    0.2, ''from_logits'': False}}}, ''aug_x'': {''ColorJitter'': {''brightness'':
    0.2, ''contrast'': 0.2, ''saturation'': 0.2}, ''GaussianBlur'': {''kernel_size'':
    [3, 5], ''sigma'': [1e-05, 1.0]}}, ''aug_xy'': {''RandomVerticalFlip'': {''p'':
    0.5}, ''RandomHorizontalFlip'': {''p'': 0.5}, ''RandomResize'': {''min_size'':
    160, ''max_size'': 224}, ''RandomRotation'': {''degrees'': 3}, ''RandomCrop'':
    {''size'': 160}}, ''pore_gen'': {''pore_size_range'': [1.4, 2.0], ''n_gaussians'':
    3, ''intensity_drop_range'': [0.3, 0.7], ''pore_generation_ratio'': 1.0, ''thresh_intensity'':
    0.17, ''noise_intensity'': 0.2, ''p_flat'': 0.1, ''sharp_factor_range'': [1, 2],
    ''pow_range'': [10, 11], ''adaptive_prob'': False, ''p_mul'': 0.6}, ''mask_thresh'':
    0.45, ''pred_thresh'': 0.5, ''eval_every'': 10, ''stride_factor'': 0.8, ''demo_pores'':
    False, ''save_model'': True, ''show'': True, ''model'': {''name'': ''resnet18'',
    ''input_channels'': ''1 + False'', ''encoder_depth'': 2, ''decoder_channels'':
    [128, 16], ''decoder_use_batchnorm'': ''True'', ''load_weights'': True, ''dropout'':
    0.0, ''encoder_weights'': ''imagenet''}, ''data_loader_params'': {''batch_size'':
    64, ''shuffle'': True, ''num_workers'': 8, ''persistent_workers'': False, ''pin_memory'':
    False}, ''ensemble_models'': 8}'
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1732012898.0
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 13
      - 16
      - 23
      4: 3.10.4
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
